config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :departments
    resources :skills
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/skill.rb
class Skill < ApplicationRecord
    validates :name, presence: true
    has_many :user_skill
    has_many :user, through: :user_skill
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < ApplicationController
    def index
        @skills = Skill.all
    end
    def show
        @skill = Skill.find(params[:id])
    end
    def new
        @skill = Skill.new
    end
    def create
        @skill = Skill.new(skill_params)
        if @skill.save
        redirect_to admin_skill_path(@skill)
        else
        render :new, status: :unprocessable_entity
        end
    end
    def edit
        @skill = Skill.find(params[:id])
    end
    def update
        @skill = Skill.find(params[:id])
    
        if @skill.update(skill_params)
        redirect_to admin_skill_path(@skill)
        else
        render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @skill = Skill.find(params[:id])
        @skill.destroy
        redirect_to admin_skills_path, status: :see_other
    end
    private
    def skill_params
        params.require(:skill).permit(:name)
    end
end

app/helpers/admin/skills_helper.rb
module Admin::SkillsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/admin/skills/_form.html.erb
<%= form_with model: skill, url: skill.persisted? ? admin_skill_path(skill) : admin_skills_path do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <% skill.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <%= form.submit %>
<% end %>

app/views/admin/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render "form", skill: @skill %>

app/views/admin/skills/index.html.erb
<h1>Skills</h1>
<ul>
    <% @skills.each do |skill|%>
        <li><%= link_to skill.name, admin_skill_path(skill) %></li>
    <% end %>
</ul>
<%= link_to "New Skill", new_admin_skill_path %>

app/views/admin/skills/new.html.erb
<h1>New Skill</h1>

<%= render "form", skill: @skill %>

app/views/admin/skills/show.html.erb
<h1><%= @skill.name %></h1>

<p>id:          <%= @skill.id %></p>
<p>name:        <%= @skill.name %></p>

<ul>
    <li><%= link_to "Edit", edit_admin_skill_path(@skill) %></li>
    <li><%= link_to "Destroy", admin_skill_path(@skill), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    } %></li>
</ul>