config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :departments
    resources :skills
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/department.rb
class Department < ApplicationRecord
    validates :department_name, presence: true
    
    belongs_to :user, optional: true
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
    def index
        @departments = Department.all
    end
    def show
        @department = Department.find(params[:id])
    end
    def new
        @department = Department.new
    end
    def create
        @department = Department.new(department_params)
        if @department.save
            redirect_to admin_department_path(@department)
        else
            render :new, status: :unprocessable_entity
        end
    end
    def edit
        @department = Department.find(params[:id])
    end
    def update
        @department = Department.find(params[:id])
    
        if @department.update(department_params)
            redirect_to admin_department_path(@department)
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @department = Department.find(params[:id])
        @department.destroy
        redirect_to admin_departments_path, status: :see_other
    end
    private
    def department_params
        params.require(:department).permit(:department_name)
    end
end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admin/departments/_form.html.erb
<%= form_with model: department, url: department.persisted? ? admin_department_path(department) : admin_departments_path do |form| %>
    <div class="field">
      <%= form.label :department_name %>
      <%= form.text_field :department_name %>
      <% department.errors.full_messages_for(:department_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <%= form.submit %>
<% end %>

app/views/admin/departments/edit.html.erb
<h1>Edit department</h1>

<%= render "form", department: @department %>

app/views/admin/departments/index.html.erb
<h1>Departments</h1>
<ul>
    <% @departments.each do |department|%>
        <li><%= link_to department.department_name, admin_department_path(department) %></li>
    <% end %>
</ul>
<%= link_to "New Department", new_admin_department_path %>

app/views/admin/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

app/views/admin/departments/show.html.erb
<h1><%= @department.department_name %></h1>

<p>id:          <%= @department.id %></p>
<p>name:        <%= @department.department_name %></p>

<ul>
    <li><%= link_to "Edit", edit_admin_department_path(@department) %></li>
    <li><%= link_to "Destroy", admin_department_path(@department), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    } %></li>
</ul>