config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :departments
    resources :skills
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
    enum address1:{
    北海道:"1",青森県:"2",岩手県:"3",宮城県:"4",秋田県:"5",山形県:"6",福島県:"7",
    茨城県:"8",栃木県:"9",群馬県:"10",埼玉県:"11",千葉県:"12",東京都:"13",神奈川県:"14",
    新潟県:"15",富山県:"16",石川県:"17",福井県:"18",山梨県:"19",長野県:"20",
    岐阜県:"21",静岡県:"22",愛知県:"23",三重県:"24",
    滋賀県:"25",京都府:"26",大阪府:"27",兵庫県:"28",奈良県:"29",和歌山県:"30",
    鳥取県:"31",島根県:"32",岡山県:"33",広島県:"34",山口県:"35",
    徳島県:"36",香川県:"37",愛媛県:"38",高知県:"39",
    福岡県:"40",佐賀県:"41",長崎県:"42",熊本県:"43",大分県:"44",宮崎県:"45",鹿児島県:"46",
    沖縄県:"47"
    }
    enum sex: {
        男性:"1", 女性:"2", その他:"3"
    }
    validates :id, presence: true, uniqueness: true
    validates :name, presence: true
    validates :ruby, presence: true
    validates :sex, presence: true, inclusion: { in: sexes.keys, message: "%{value} is not a valid sex" }
    validates :tel, allow_blank: true, format: { with: /\A0[-\d]{9,12}\z/, message: "must be a valid phone number" }
    validates :mobile, allow_blank: true, format: { with: /\A0[5789]0[-]?\d{4}[-]?\d{4}\z/, message: "must be a valid mobile number" }
    validates :mail, presence: true, uniqueness: true, format: { with: /\A[\w+-.@?]+/i, message: "must be a valid email address" }
    validates :zip, presence: true, format: { with: /\A\d{3}-?\d{4}\z/, message: "must be a valid postal code" }  
    validates :address1, presence: true, inclusion: { in: address1s.keys }
    validates :birthday, presence: true

    belongs_to :department, optional: true
    has_many :user_skill
    has_many :skill, through: :user_skill
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to admin_user_path(@user)
        else
            render :new, status: :unprocessable_entity
        end
    end
    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to admin_user_path(@user)
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy

        redirect_to admin_users_path, status: :see_other
    end

    private
    def user_params
        params.require(:user).permit(:id, :department_id, :name, :ruby, :sex, :tel, :mobile, :mail, :zip, :address1, :address2, :address3, :address4, :address5, :birthday, skill_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
end
def show
    @user = User.find(params[:id])
end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def format_user_name(user)
        "User: #{user.name}"
    end
    def user_greeting(user)
        "Hello, #{user.name}!"
    end

end

app/views/admin/users/_form.html.erb
<%= form_with model: @user, url: user.persisted? ? admin_user_path(user) : admin_users_path  do |form| %>
    <div class="field">
      <%= form.label :id %>
      <%= form.text_field :id %>
      <% user.errors.full_messages_for(:id).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    
    <div class="field">
      <%= form.label :department_id %>
      <%= form.collection_select :department_id, Department.all, :id, :department_name, prompt: '選択してください' %>
      <% user.errors.full_messages_for(:department_id).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <% user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :ruby %>
      <%= form.text_field :ruby %>
      <% user.errors.full_messages_for(:ruby).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :sex %>
      <%= form.select :sex, options_for_select(User.sexes.keys.map { |key| [key.humanize, key] }, selected: @user.sex), prompt: "選択してください" %>
      <% user.errors.full_messages_for(:sex).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :tel %>
      <%= form.text_field :tel %>
      <% user.errors.full_messages_for(:tel).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :mobile %>
      <%= form.text_field :mobile %>
      <% user.errors.full_messages_for(:mobile).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :mail %>
      <%= form.email_field :mail %>
      <% user.errors.full_messages_for(:mail).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :zip %>
      <%= form.text_field :zip %>
      <% user.errors.full_messages_for(:zip).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :address1 %>
      <%= form.select :address1, options_for_select(User.address1s.keys.map { |key| [key.humanize, key] }, selected: @user.address1), prompt: "選択してください" %>
      <% user.errors.full_messages_for(:address1).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :address2 %>
      <%= form.text_field :address2 %>
    </div>

    <div class="field">
      <%= form.label :address3 %>
      <%= form.text_field :address3 %>
    </div>

    <div class="field">
      <%= form.label :address4 %>
      <%= form.text_field :address4 %>
    </div>

    <div class="field">
      <%= form.label :address5 %>
      <%= form.text_field :address5 %>
    </div>

    <div class="field">
      <%= form.label :birthday %>
      <%= form.date_select :birthday %>
      <% user.errors.full_messages_for(:birthday).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :skills, "Select Skills" %>
      <%= form.collection_check_boxes :skill_ids, Skill.all, :id, :name do |cb| %>
        <div>
          <%= cb.check_box %>
          <%= cb.label %>
        </div>
      <% end %>
      <% user.errors.full_messages_for(:skills).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <%= form.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<ul>
    <% @users.each do |user|%>
        <li><%= link_to user.name, admin_user_path(user) %></li>
    <% end %>
</ul>
<%= link_to "New User", new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %></h1>

<p>id:          <%= @user.id %></p>
<p>department_name: <%= @user.department&.department_name || '無所属です' %></p>
<p>name:        <%= @user.name %></p>
<p>ruby:        <%= @user.ruby %></p>
<p>sex:         <%= I18n.t("user.sex.#{@user.sex}") %></p>
<p>tel:         <%= @user.tel %></p>
<p>mobile:      <%= @user.mobile %></p>
<p>mail:        <%= @user.mail %></p>
<p>zip:         <%= @user.zip %></p>
<p>address1:    <%= @user.address1 %></p>
<p>address2:    <%= @user.address2 %></p>
<p>address3:    <%= @user.address3 %></p>
<p>address4:    <%= @user.address4 %></p>
<p>address5:    <%= @user.address5 %></p>
<p>birthday:    <%= @user.birthday %></p>
<p>Skills:</p>
<ul>
  <% @user.skill.each do |skill| %>
    <li><%= skill.name %></li>
  <% end %>
</ul>


<ul>
    <li><%= link_to "Edit", edit_admin_user_path(@user) %></li>
    <li><%= link_to "Destroy", admin_user_path(@user), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    } %></li>
</ul>